version: '3'
services:

  # The Application
  app:
    image: myrepo/laravel-app
    working_dir: /var/www
    volumes:
      - /var/www/storage
    environment:
      - "DB_HOST=database"
      - "REDIS_HOST=cache"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    tty: true
    ports:
      - "9000:9000"

  # The Web Server
  web:
    image: myrepo/laravel-web
    ports:
      - 80:80
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    depends_on:
      - app

  # The Database
  database:
    image: mysql:latest
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33061:3306"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  # redis
  cache:
    image: redis:3.0-alpine

volumes:
  dbdata:
